name: Simple Python Action

on:
  repository_dispatch:
    types: [run-script]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run Python script
        run: python print_script.py
        
      - name: Create output file
        run: echo "Script ran at $(date)" > output.txt
        
      # Updated version of the upload-artifact action
      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output.txt
